import { Apartment, Unit, Review } from './types';
import {
  BALCONY_VIEW_IMAGE,
  BEDROOM_SUITE_IMAGE,
  EXTERIOR_FACADE_IMAGE,
  LIVING_ROOM_IMAGE,
  MODERN_KITCHEN_IMAGE,
} from './imageAssets';

export const APARTMENT_DATA: Apartment = {
  id: 'aradad-adjiringanor',
  name: 'Aradad Homes',
  address: 'Nii Kwei Mensah Street',
  city: 'Accra',
  neighborhood: 'Adjiringanor',
  country: 'Ghana',
  landmarks: 'Opposite Galaxy International School, Adjiringanor',
  ownerName: 'James M. Nartey',
  ownerPhone: '+233 55 097 7992',
  ownerEmail: 'aradadhomes@gmail.com',
  payoutAccount: {
    name: 'ARADAD HOMES',
    number: '1400011105469',
    branch: 'Osu',
    swiftCode: 'ACCCGHAC',
  },
};

export const INITIAL_UNITS: Unit[] = [
  {
    id: 'aradad-3bed',
    apartmentId: 'aradad-adjiringanor',
    title: 'The Royal 3-Bedroom Luxury Apartment',
    subtitle: 'Three Private En-Suite Bedrooms · Expansive Living Suite · Dual Balconies',
    propertyType: '3+ Bedroom Luxury',
    category: 'apartment',
    bedrooms: 3,
    bathrooms: 3,
    maxOccupancy: 4,
    nightlyRate: 230,
    weeklyMonthlyRate: 3000,
    currency: 'USD',
    minimumStay: 1,
    maximumStay: 30,
    cleaningFee: 0,
    securityDeposit: 300,
    prepaidElectricityGhc: 500,
    checkInTime: '15:00',
    checkOutTime: '11:00',
    bookingStyle: 'instant',
    description:
      'Our 3-bedroom apartment offers an expanded, luxury layout designed to comfortably accommodate larger families, groups, or guests who desire extra space, privacy, and upscale comfort. Each bedroom features built-in wardrobes, premium queen/king-sized mattresses, luxury bedding, and individual split air conditioning units to ensure personal comfort for every guest. Includes an expansive open-concept living area with deep-cushioned sofa suite, large Smart TV, dedicated dining area, and a fully fitted modern kitchen with double-door refrigerator.',
    amenities: [
      'High-Speed Starlink Wi-Fi',
      '24/7 Automatic Standby Generator',
      'Dedicated Water Reservoirs & Pump',
      'Individual Split AC in All Rooms',
      '24/7 Gated Security & CCTV Coverage',
      'Designated On-Site Parking',
      'Fully Fitted Modern Kitchen (Double-Door Fridge, Oven, Microwave, Kettle)',
      'Washer & Laundry Setup',
      'Large Smart TV with Streaming',
      'Private Scenic Balconies',
      'Complimentary Housekeeping & Fresh Linens',
      'GH₵ 500.00 Initial Prepaid Electricity Credit',
    ],
    images: [
      EXTERIOR_FACADE_IMAGE,
      LIVING_ROOM_IMAGE,
      BEDROOM_SUITE_IMAGE,
      MODERN_KITCHEN_IMAGE,
      BALCONY_VIEW_IMAGE,
    ],
    rooms: [
      {
        id: 'room-3b-1',
        unitId: 'aradad-3bed',
        name: 'Master Presidential En-Suite Suite',
        bedType: 'King Bed',
        hasPrivateBath: true,
        hasAc: true,
        hasWardrobe: true,
        weeklyRate: 618,
        monthlyRate: 2185,
        preferredPeriod: 'week',
        currency: 'USD',
        maxGuests: 2,
        description: 'Features a king bed, private en-suite bathroom with walk-in shower, built-in wardrobes, and private terrace access.',
        images: [BEDROOM_SUITE_IMAGE],
        isActive: true,
      },
      {
        id: 'room-3b-2',
        unitId: 'aradad-3bed',
        name: 'Deluxe Queen En-Suite Room',
        bedType: 'Queen Bed',
        hasPrivateBath: true,
        hasAc: true,
        hasWardrobe: true,
        weeklyRate: 520,
        monthlyRate: 1840,
        preferredPeriod: 'week',
        currency: 'USD',
        maxGuests: 2,
        description: 'Serene bedroom with comfortable queen-sized bed, en-suite bathroom, split AC, and ample closet storage.',
        images: [BEDROOM_SUITE_IMAGE],
        isActive: true,
      },
      {
        id: 'room-3b-3',
        unitId: 'aradad-3bed',
        name: 'Cozy En-Suite Bedroom 3',
        bedType: 'Queen Bed',
        hasPrivateBath: true,
        hasAc: true,
        hasWardrobe: true,
        weeklyRate: 488,
        monthlyRate: 1725,
        preferredPeriod: 'week',
        currency: 'USD',
        maxGuests: 2,
        description: 'Quiet, beautifully furnished bedroom with dedicated bathroom, writing space, and silent air conditioning.',
        images: [BEDROOM_SUITE_IMAGE],
        isActive: true,
      },
    ],
    isActive: true,
  },
  {
    id: 'aradad-2bed',
    apartmentId: 'aradad-adjiringanor',
    title: 'The Executive 2-Bedroom Short-Let Apartment',
    subtitle: 'Two Private En-Suite Bedrooms · Open-Plan Living & Dining · Peaceful Balcony',
    propertyType: '2 Bedroom Short-let',
    category: 'apartment',
    bedrooms: 2,
    bathrooms: 3,
    maxOccupancy: 3,
    nightlyRate: 130,
    weeklyMonthlyRate: 2000,
    currency: 'USD',
    minimumStay: 1,
    maximumStay: 30,
    cleaningFee: 0,
    securityDeposit: 300,
    prepaidElectricityGhc: 350,
    checkInTime: '15:00',
    checkOutTime: '11:00',
    bookingStyle: 'instant',
    description:
      'Our 2-bedroom short-let apartment is designed as a modern, upscale space tailored for short stays, vacation rentals, and staycations. Features two en-suite bedrooms fully furnished with plush double/queen beds, high-end linens, fitted wardrobes, and dedicated air-conditioning. An open-plan living and dining area with ambient lighting and flat-screen smart TV, fully equipped self-catering kitchen with modern appliances, and a private balcony overlooking Adjiringanor.',
    amenities: [
      'High-Speed Starlink Wi-Fi',
      '24/7 Standby Generator Backup',
      'High-Capacity Water Reservoirs',
      'Individual Split ACs in Every Room',
      '24/7 Gated Security & CCTV Coverage',
      'Designated Multi-Vehicle Parking Space',
      'Fully Equipped Kitchen (Cooktop, Microwave, Fridge, Kettle, Cookware)',
      'Washer & Cleaning Services',
      'Flat-Screen Smart TV with Streaming',
      'Private Outdoor Balcony with Natural Light',
      'Hot Water Showers & Vanity Mirrors',
      'GH₵ 350.00 Initial Prepaid Electricity Credit',
    ],
    images: [
      LIVING_ROOM_IMAGE,
      BEDROOM_SUITE_IMAGE,
      MODERN_KITCHEN_IMAGE,
      BALCONY_VIEW_IMAGE,
      EXTERIOR_FACADE_IMAGE,
    ],
    rooms: [
      {
        id: 'room-2b-1',
        unitId: 'aradad-2bed',
        name: 'Executive Master En-Suite Room',
        bedType: 'Queen Bed',
        hasPrivateBath: true,
        hasAc: true,
        hasWardrobe: true,
        weeklyRate: 488,
        monthlyRate: 1725,
        preferredPeriod: 'week',
        currency: 'USD',
        maxGuests: 2,
        description: 'Master bedroom with en-suite bath, plush double/queen bed, vanity mirror, and quiet split AC.',
        images: [BEDROOM_SUITE_IMAGE],
        isActive: true,
      },
      {
        id: 'room-2b-2',
        unitId: 'aradad-2bed',
        name: 'Deluxe Guest En-Suite Room',
        bedType: 'Double Bed',
        hasPrivateBath: true,
        hasAc: true,
        hasWardrobe: true,
        weeklyRate: 423,
        monthlyRate: 1495,
        preferredPeriod: 'week',
        currency: 'USD',
        maxGuests: 2,
        description: 'Comfortable guest bedroom with en-suite shower, fitted closet, and high thread-count linens.',
        images: [BEDROOM_SUITE_IMAGE],
        isActive: true,
      },
    ],
    isActive: true,
  },
];

export const HOUSE_RULES = {
  privileges: [
    {
      title: 'Complimentary Starlink Wi-Fi',
      desc: 'High-speed Starlink Wi-Fi is provided free of charge throughout your entire stay with zero data caps.',
    },
    {
      title: 'Prepaid Electricity Allowance',
      desc: 'Enjoy a complimentary initial credit of GH₵ 500.00 (3-Bed) or GH₵ 350.00 (2-Bed) for power. If depleted, guests can purchase top-ups.',
    },
    {
      title: 'Designated On-Site Parking',
      desc: 'Access to designated on-site parking spaces inside the gated compound for registered vehicles.',
    },
    {
      title: 'Full Property Amenities',
      desc: 'Safe, private access to the apartment, balcony, laundry washer, and fully fitted modern kitchen.',
    },
  ],
  rules: [
    {
      title: '1. Occupancy & Check-In',
      points: [
        'Guest Limit: Maximum of 6 guests total (or maximum stated per apartment). Unregistered overnight guests are strictly not permitted.',
        'Identification: Primary guest must provide a valid government photo ID, phone number, and address at check-in.',
        'Check-In / Check-Out: Standard check-in is at 3:00 PM (15:00); check-out is at 11:00 AM. Early arrivals or late departures require prior written host approval.',
      ],
    },
    {
      title: '2. Sound & Neighborhood Courtesy (Zero Tolerance)',
      points: [
        'NO Speakers / NO Amplified Sound: Bluetooth speakers, DJ equipment, PA systems, subwoofers, or external sound systems are strictly prohibited at all times indoors and outdoors.',
        'Quiet Hours: 10:00 PM – 8:00 AM daily. Please keep noise levels respectful during these hours.',
        'No Parties or Commercial Events: Large parties are strictly forbidden. Intimate gatherings require prior host approval.',
      ],
    },
    {
      title: '3. Parking Restrictions',
      points: [
        'Park only in designated areas on the compound.',
        'No street parking, blocking driveways, sidewalks, or neighbor access.',
        'Unauthorized parking will result in towing at vehicle owner’s expense.',
      ],
    },
    {
      title: '4. Property Care & Security',
      points: [
        'No Indoor Smoking: Smoking of any kind (cigarettes, shisha/hookah, cannabis, vapes) indoors is strictly prohibited.',
        'Security Devices: Do not tamper with, unplug, or cover Starlink routers, Ring doorbells, or exterior security cameras.',
        'Waste Management: Dispose of waste properly using provided bins; do not allow trash to overflow or leave bags outdoors.',
        'Damages & Cleanliness: Guests are responsible for keeping space tidy. Excessive dirtiness, glitter/confetti, linen stains, or missing items will result in deductions from the $300 refundable security deposit.',
      ],
    },
  ],
};

export const CANCELLATION_POLICY = {
  hostInitiated: {
    title: '1. Host-Initiated Termination',
    desc: 'If host terminates tenancy during stay: Tenant receives 100% refund of all unstayed nights, minus documented damages. Payout returned via original payment method within 1–3 business days following property inspection.',
  },
  tenantInitiated: {
    title: '2. Tenant-Initiated Termination',
    desc: 'If tenant elects to cancel or terminate tenancy during stay: Tenant is eligible for up to 70% maximum refund for all remaining unstayed nights, minus documented damages. The host retains 30% of the remaining reservation value to cover operational costs and calendar blockages.',
  },
  damageAssessment: {
    title: '3. Damage Assessment & Security Deposit ($300)',
    desc: 'Property damages, if any, will be assessed and itemized within 48 hours of termination. The refundable $300 deposit or remaining balance will be returned via the original payment method within 1–3 business days following inspection.',
  },
};

export const DEFAULT_SITE_SETTINGS = {
  siteName: 'Aradad Homes',
  domain: 'adradhomesgh.com',
  tagline: 'Private En-Suite Rooms in Adjiringanor, Accra',
  address: 'Nii Kwei Mensah Street',
  neighborhood: 'Adjiringanor',
  city: 'Accra',
  country: 'Ghana',
  landmarks: 'Opposite Galaxy International School',
  ownerName: 'James M. Nartey',
  ownerPhone: '+233 55 097 7992',
  ownerEmail: 'aradadhomes@gmail.com',
  bankAccountName: 'ARADAD HOMES',
  bankAccountNumber: '1400011105469',
  bankBranch: 'Osu, Accra',
  bankSwiftCode: 'ACCCGHAC',
  defaultCheckInTime: '15:00',
  defaultCheckOutTime: '11:00',
  defaultSecurityDeposit: 300,
  usdToGhsRate: 15.5,
  quietHours: '10:00 PM – 8:00 AM daily',
  starlinkNetworkName: 'Aradad_Starlink_HighSpeed',
  poweredBy: 'JAMS TECH',
};
